#https://www.delftstack.com/howto/docker/docker-create-directory/#:~:text=The%20command%20RUN%20mkdir%20%2Dp,using%20the%20above%20Docker%20file.
#follow the url for Dockerfile creation 

FROM openjdk:8-jdk-alpine	
COPY testprj-1.0-SNAPSHOT.jar /home/testprj-1.0-SNAPSHOT.jar	
CMD ["java","-jar","/home/testprj-1.0-SNAPSHOT.jar"]	


#create a folder in /opt  like test				
#copy the jar file in the created folder test in opt and also create the dockerfile in the test folder				
#[ The jar file should be in the path where the dockerfile is present then only it will work]				
